"""more user fields

Revision ID: 1751b765c9db
Revises: 4ca38c841595
Create Date: 2016-05-28 05:27:06.028975

"""

# revision identifiers, used by Alembic.
revision = '1751b765c9db'
down_revision = '4ca38c841595'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('num_adults', sa.SmallInteger(), nullable=True))
    op.add_column('users', sa.Column('num_capacity', sa.SmallInteger(), nullable=True))
    op.add_column('users', sa.Column('num_children', sa.SmallInteger(), nullable=True))
    op.add_column('users', sa.Column('pref_10_to_18', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('pref_1_to_5', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('pref_6_to_9', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('pref_behavioral', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('pref_boys', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('pref_girls', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('pref_respite', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('pref_siblings', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pref_siblings')
    op.drop_column('users', 'pref_respite')
    op.drop_column('users', 'pref_girls')
    op.drop_column('users', 'pref_boys')
    op.drop_column('users', 'pref_behavioral')
    op.drop_column('users', 'pref_6_to_9')
    op.drop_column('users', 'pref_1_to_5')
    op.drop_column('users', 'pref_10_to_18')
    op.drop_column('users', 'num_children')
    op.drop_column('users', 'num_capacity')
    op.drop_column('users', 'num_adults')
    ### end Alembic commands ###
