"""image blob

Revision ID: 478e3127a0e5
Revises: c79098887777
Create Date: 2016-06-03 17:10:12.783293

"""

# revision identifiers, used by Alembic.
revision = '478e3127a0e5'
down_revision = 'c79098887777'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_image', sa.LargeBinary(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image')
    ### end Alembic commands ###
