"""user fields

Revision ID: 4ca38c841595
Revises: 783e2c4f851d
Create Date: 2016-05-28 04:12:25.598975

"""

# revision identifiers, used by Alembic.
revision = '4ca38c841595'
down_revision = '783e2c4f851d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('blurb', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('license_number', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'license_number')
    op.drop_column('users', 'blurb')
    op.drop_column('users', 'address')
    ### end Alembic commands ###
