"""photo column

Revision ID: c79098887777
Revises: eef6112170df
Create Date: 2016-06-01 18:55:39.714455

"""

# revision identifiers, used by Alembic.
revision = 'c79098887777'
down_revision = 'eef6112170df'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_photo', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_photo')
    ### end Alembic commands ###
