//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.Natoma.HhsPrototype.UserInterface.HhsPrototypeProc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserProfile", Namespace="http://schemas.datacontract.org/2004/07/Com.Natoma.HhsPrototype.Proc.DataContract" +
        "s")]
    [System.SerializableAttribute()]
    public partial class UserProfile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdditionalHouseholdLanguagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdditionalLanguagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> CapacityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CertificationInformationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmploymentInformationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EthnicityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FingerprintedAlternateCareProvidersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FingerprintingInformationField;
        
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsApprovedForAdoptiveCareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsApprovedForKinshipCareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAvailableForPetsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KidsField;
        
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaritalStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NeighborhoodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> NumberOfAdultsInHouseholdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> NumberOfDependentsInHouseholdField;
        
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PetsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimaryHouseholdLanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimaryLanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SchoolDistrictInformationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpecialCarePreferencesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrainingInformationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> UidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalHouseholdLanguages {
            get {
                return this.AdditionalHouseholdLanguagesField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalHouseholdLanguagesField, value) != true)) {
                    this.AdditionalHouseholdLanguagesField = value;
                    this.RaisePropertyChanged("AdditionalHouseholdLanguages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalLanguages {
            get {
                return this.AdditionalLanguagesField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalLanguagesField, value) != true)) {
                    this.AdditionalLanguagesField = value;
                    this.RaisePropertyChanged("AdditionalLanguages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine1 {
            get {
                return this.AddressLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine1Field, value) != true)) {
                    this.AddressLine1Field = value;
                    this.RaisePropertyChanged("AddressLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine2 {
            get {
                return this.AddressLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine2Field, value) != true)) {
                    this.AddressLine2Field = value;
                    this.RaisePropertyChanged("AddressLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> Capacity {
            get {
                return this.CapacityField;
            }
            set {
                if ((this.CapacityField.Equals(value) != true)) {
                    this.CapacityField = value;
                    this.RaisePropertyChanged("Capacity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CertificationInformation {
            get {
                return this.CertificationInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.CertificationInformationField, value) != true)) {
                    this.CertificationInformationField = value;
                    this.RaisePropertyChanged("CertificationInformation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmploymentInformation {
            get {
                return this.EmploymentInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.EmploymentInformationField, value) != true)) {
                    this.EmploymentInformationField = value;
                    this.RaisePropertyChanged("EmploymentInformation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ethnicity {
            get {
                return this.EthnicityField;
            }
            set {
                if ((object.ReferenceEquals(this.EthnicityField, value) != true)) {
                    this.EthnicityField = value;
                    this.RaisePropertyChanged("Ethnicity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FingerprintedAlternateCareProviders {
            get {
                return this.FingerprintedAlternateCareProvidersField;
            }
            set {
                if ((object.ReferenceEquals(this.FingerprintedAlternateCareProvidersField, value) != true)) {
                    this.FingerprintedAlternateCareProvidersField = value;
                    this.RaisePropertyChanged("FingerprintedAlternateCareProviders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FingerprintingInformation {
            get {
                return this.FingerprintingInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.FingerprintingInformationField, value) != true)) {
                    this.FingerprintingInformationField = value;
                    this.RaisePropertyChanged("FingerprintingInformation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsApprovedForAdoptiveCare {
            get {
                return this.IsApprovedForAdoptiveCareField;
            }
            set {
                if ((this.IsApprovedForAdoptiveCareField.Equals(value) != true)) {
                    this.IsApprovedForAdoptiveCareField = value;
                    this.RaisePropertyChanged("IsApprovedForAdoptiveCare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsApprovedForKinshipCare {
            get {
                return this.IsApprovedForKinshipCareField;
            }
            set {
                if ((this.IsApprovedForKinshipCareField.Equals(value) != true)) {
                    this.IsApprovedForKinshipCareField = value;
                    this.RaisePropertyChanged("IsApprovedForKinshipCare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAvailableForPets {
            get {
                return this.IsAvailableForPetsField;
            }
            set {
                if ((this.IsAvailableForPetsField.Equals(value) != true)) {
                    this.IsAvailableForPetsField = value;
                    this.RaisePropertyChanged("IsAvailableForPets");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kids {
            get {
                return this.KidsField;
            }
            set {
                if ((object.ReferenceEquals(this.KidsField, value) != true)) {
                    this.KidsField = value;
                    this.RaisePropertyChanged("Kids");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaritalStatus {
            get {
                return this.MaritalStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.MaritalStatusField, value) != true)) {
                    this.MaritalStatusField = value;
                    this.RaisePropertyChanged("MaritalStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Neighborhood {
            get {
                return this.NeighborhoodField;
            }
            set {
                if ((object.ReferenceEquals(this.NeighborhoodField, value) != true)) {
                    this.NeighborhoodField = value;
                    this.RaisePropertyChanged("Neighborhood");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> NumberOfAdultsInHousehold {
            get {
                return this.NumberOfAdultsInHouseholdField;
            }
            set {
                if ((this.NumberOfAdultsInHouseholdField.Equals(value) != true)) {
                    this.NumberOfAdultsInHouseholdField = value;
                    this.RaisePropertyChanged("NumberOfAdultsInHousehold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> NumberOfDependentsInHousehold {
            get {
                return this.NumberOfDependentsInHouseholdField;
            }
            set {
                if ((this.NumberOfDependentsInHouseholdField.Equals(value) != true)) {
                    this.NumberOfDependentsInHouseholdField = value;
                    this.RaisePropertyChanged("NumberOfDependentsInHousehold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pets {
            get {
                return this.PetsField;
            }
            set {
                if ((object.ReferenceEquals(this.PetsField, value) != true)) {
                    this.PetsField = value;
                    this.RaisePropertyChanged("Pets");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimaryHouseholdLanguage {
            get {
                return this.PrimaryHouseholdLanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryHouseholdLanguageField, value) != true)) {
                    this.PrimaryHouseholdLanguageField = value;
                    this.RaisePropertyChanged("PrimaryHouseholdLanguage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimaryLanguage {
            get {
                return this.PrimaryLanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryLanguageField, value) != true)) {
                    this.PrimaryLanguageField = value;
                    this.RaisePropertyChanged("PrimaryLanguage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Race {
            get {
                return this.RaceField;
            }
            set {
                if ((object.ReferenceEquals(this.RaceField, value) != true)) {
                    this.RaceField = value;
                    this.RaisePropertyChanged("Race");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SchoolDistrictInformation {
            get {
                return this.SchoolDistrictInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.SchoolDistrictInformationField, value) != true)) {
                    this.SchoolDistrictInformationField = value;
                    this.RaisePropertyChanged("SchoolDistrictInformation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpecialCarePreferences {
            get {
                return this.SpecialCarePreferencesField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecialCarePreferencesField, value) != true)) {
                    this.SpecialCarePreferencesField = value;
                    this.RaisePropertyChanged("SpecialCarePreferences");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrainingInformation {
            get {
                return this.TrainingInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.TrainingInformationField, value) != true)) {
                    this.TrainingInformationField = value;
                    this.RaisePropertyChanged("TrainingInformation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> Uid {
            get {
                return this.UidField;
            }
            set {
                if ((this.UidField.Equals(value) != true)) {
                    this.UidField = value;
                    this.RaisePropertyChanged("Uid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/Com.Natoma.HhsPrototype.Proc.DataContract" +
        "s")]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string BodyField;
        
        private System.DateTime DateSentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsFlaggedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsReadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RecipientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SenderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long UserProfileIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime DateSent {
            get {
                return this.DateSentField;
            }
            set {
                if ((this.DateSentField.Equals(value) != true)) {
                    this.DateSentField = value;
                    this.RaisePropertyChanged("DateSent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFlagged {
            get {
                return this.IsFlaggedField;
            }
            set {
                if ((this.IsFlaggedField.Equals(value) != true)) {
                    this.IsFlaggedField = value;
                    this.RaisePropertyChanged("IsFlagged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRead {
            get {
                return this.IsReadField;
            }
            set {
                if ((this.IsReadField.Equals(value) != true)) {
                    this.IsReadField = value;
                    this.RaisePropertyChanged("IsRead");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSent {
            get {
                return this.IsSentField;
            }
            set {
                if ((this.IsSentField.Equals(value) != true)) {
                    this.IsSentField = value;
                    this.RaisePropertyChanged("IsSent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((this.MessageIdField.Equals(value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MessageType {
            get {
                return this.MessageTypeField;
            }
            set {
                if ((this.MessageTypeField.Equals(value) != true)) {
                    this.MessageTypeField = value;
                    this.RaisePropertyChanged("MessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RecipientId {
            get {
                return this.RecipientIdField;
            }
            set {
                if ((this.RecipientIdField.Equals(value) != true)) {
                    this.RecipientIdField = value;
                    this.RaisePropertyChanged("RecipientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SenderId {
            get {
                return this.SenderIdField;
            }
            set {
                if ((this.SenderIdField.Equals(value) != true)) {
                    this.SenderIdField = value;
                    this.RaisePropertyChanged("SenderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UserProfileId {
            get {
                return this.UserProfileIdField;
            }
            set {
                if ((this.UserProfileIdField.Equals(value) != true)) {
                    this.UserProfileIdField = value;
                    this.RaisePropertyChanged("UserProfileId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HhsPrototypeProc.IProtoProcSvc")]
    public interface IProtoProcSvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProtoProcSvc/CreateUserProfile", ReplyAction="http://tempuri.org/IProtoProcSvc/CreateUserProfileResponse")]
        long CreateUserProfile(Com.Natoma.HhsPrototype.UserInterface.HhsPrototypeProc.UserProfile userProfile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProtoProcSvc/CreateUserProfile", ReplyAction="http://tempuri.org/IProtoProcSvc/CreateUserProfileResponse")]
        System.Threading.Tasks.Task<long> CreateUserProfileAsync(Com.Natoma.HhsPrototype.UserInterface.HhsPrototypeProc.UserProfile userProfile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProtoProcSvc/UpdateUserProfile", ReplyAction="http://tempuri.org/IProtoProcSvc/UpdateUserProfileResponse")]
        bool UpdateUserProfile(Com.Natoma.HhsPrototype.UserInterface.HhsPrototypeProc.UserProfile userProfile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProtoProcSvc/UpdateUserProfile", ReplyAction="http://tempuri.org/IProtoProcSvc/UpdateUserProfileResponse")]
        System.Threading.Tasks.Task<bool> UpdateUserProfileAsync(Com.Natoma.HhsPrototype.UserInterface.HhsPrototypeProc.UserProfile userProfile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProtoProcSvc/SendMessage", ReplyAction="http://tempuri.org/IProtoProcSvc/SendMessageResponse")]
        long SendMessage(Com.Natoma.HhsPrototype.UserInterface.HhsPrototypeProc.Message messageToSend);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProtoProcSvc/SendMessage", ReplyAction="http://tempuri.org/IProtoProcSvc/SendMessageResponse")]
        System.Threading.Tasks.Task<long> SendMessageAsync(Com.Natoma.HhsPrototype.UserInterface.HhsPrototypeProc.Message messageToSend);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProtoProcSvc/GetMessagesForUser", ReplyAction="http://tempuri.org/IProtoProcSvc/GetMessagesForUserResponse")]
        System.Collections.Generic.List<Com.Natoma.HhsPrototype.UserInterface.HhsPrototypeProc.Message> GetMessagesForUser(long userProfileId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProtoProcSvc/GetMessagesForUser", ReplyAction="http://tempuri.org/IProtoProcSvc/GetMessagesForUserResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Com.Natoma.HhsPrototype.UserInterface.HhsPrototypeProc.Message>> GetMessagesForUserAsync(long userProfileId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProtoProcSvc/DeleteUserMessages", ReplyAction="http://tempuri.org/IProtoProcSvc/DeleteUserMessagesResponse")]
        bool DeleteUserMessages(long userProfileId, System.Collections.Generic.List<long> messageIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProtoProcSvc/DeleteUserMessages", ReplyAction="http://tempuri.org/IProtoProcSvc/DeleteUserMessagesResponse")]
        System.Threading.Tasks.Task<bool> DeleteUserMessagesAsync(long userProfileId, System.Collections.Generic.List<long> messageIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProtoProcSvc/LogIn", ReplyAction="http://tempuri.org/IProtoProcSvc/LogInResponse")]
        Com.Natoma.HhsPrototype.UserInterface.HhsPrototypeProc.UserProfile LogIn(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProtoProcSvc/LogIn", ReplyAction="http://tempuri.org/IProtoProcSvc/LogInResponse")]
        System.Threading.Tasks.Task<Com.Natoma.HhsPrototype.UserInterface.HhsPrototypeProc.UserProfile> LogInAsync(string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProtoProcSvcChannel : Com.Natoma.HhsPrototype.UserInterface.HhsPrototypeProc.IProtoProcSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProtoProcSvcClient : System.ServiceModel.ClientBase<Com.Natoma.HhsPrototype.UserInterface.HhsPrototypeProc.IProtoProcSvc>, Com.Natoma.HhsPrototype.UserInterface.HhsPrototypeProc.IProtoProcSvc {
        
        public ProtoProcSvcClient() {
        }
        
        public ProtoProcSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProtoProcSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProtoProcSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProtoProcSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public long CreateUserProfile(Com.Natoma.HhsPrototype.UserInterface.HhsPrototypeProc.UserProfile userProfile) {
            return base.Channel.CreateUserProfile(userProfile);
        }
        
        public System.Threading.Tasks.Task<long> CreateUserProfileAsync(Com.Natoma.HhsPrototype.UserInterface.HhsPrototypeProc.UserProfile userProfile) {
            return base.Channel.CreateUserProfileAsync(userProfile);
        }
        
        public bool UpdateUserProfile(Com.Natoma.HhsPrototype.UserInterface.HhsPrototypeProc.UserProfile userProfile) {
            return base.Channel.UpdateUserProfile(userProfile);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateUserProfileAsync(Com.Natoma.HhsPrototype.UserInterface.HhsPrototypeProc.UserProfile userProfile) {
            return base.Channel.UpdateUserProfileAsync(userProfile);
        }
        
        public long SendMessage(Com.Natoma.HhsPrototype.UserInterface.HhsPrototypeProc.Message messageToSend) {
            return base.Channel.SendMessage(messageToSend);
        }
        
        public System.Threading.Tasks.Task<long> SendMessageAsync(Com.Natoma.HhsPrototype.UserInterface.HhsPrototypeProc.Message messageToSend) {
            return base.Channel.SendMessageAsync(messageToSend);
        }
        
        public System.Collections.Generic.List<Com.Natoma.HhsPrototype.UserInterface.HhsPrototypeProc.Message> GetMessagesForUser(long userProfileId) {
            return base.Channel.GetMessagesForUser(userProfileId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Com.Natoma.HhsPrototype.UserInterface.HhsPrototypeProc.Message>> GetMessagesForUserAsync(long userProfileId) {
            return base.Channel.GetMessagesForUserAsync(userProfileId);
        }
        
        public bool DeleteUserMessages(long userProfileId, System.Collections.Generic.List<long> messageIds) {
            return base.Channel.DeleteUserMessages(userProfileId, messageIds);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteUserMessagesAsync(long userProfileId, System.Collections.Generic.List<long> messageIds) {
            return base.Channel.DeleteUserMessagesAsync(userProfileId, messageIds);
        }
        
        public Com.Natoma.HhsPrototype.UserInterface.HhsPrototypeProc.UserProfile LogIn(string username, string password) {
            return base.Channel.LogIn(username, password);
        }
        
        public System.Threading.Tasks.Task<Com.Natoma.HhsPrototype.UserInterface.HhsPrototypeProc.UserProfile> LogInAsync(string username, string password) {
            return base.Channel.LogInAsync(username, password);
        }
    }
}
